
trigger:
- Non-Prod

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '8.x'
  
stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: windows-latest

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/NPOMS.API.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/NPOMS.API.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/NPOMS.API.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

  - job: BuildSPAJob
    displayName: Build SPA job
    dependsOn: 
    - Build
    pool:
      vmImage: 'ubuntu-20.04'
       
    variables:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      artifactName: 'drop'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
        checkLatest: true
      displayName: 'Install Node.js'

    - script: |
        cd '$(System.DefaultWorkingDirectory)/Presentation/NPOMS.Web/ClientApp'
        npm install -g @angular/cli@11.2.19
        npm install --force
        ng build --configuration nonprod
      displayName: 'npm install and build'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Presentation/NPOMS.Web/ClientApp/dist/wwwroot'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'app'
        publishLocation: 'Container'

  - job: CreateReleaseArtifact
    displayName: 'Package for shared-hosting of angular app and web api'
    dependsOn: 
    - Build
    - BuildSPAJob
    pool:
      vmImage: windows-2019
    steps:
    - checkout: none
    - download: current

    - task: ExtractFiles@1
      inputs:
       archiveFilePatterns: '$(Pipeline.Workspace)/**/*.zip'
       destinationFolder: '$(Pipeline.Workspace)/NewPackage'
       cleanDestinationFolder: false
       overwriteExistingFiles: false

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Pipeline.Workspace)/NewPackage'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Pipeline.Workspace)/WebAPI1.zip'

    - publish: $(Pipeline.Workspace)/WebAPI1.zip
      artifact: WebAPI

- stage: 'DeployAPI'
  displayName: 'Deploy the web application'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: TapsNonProd
    #variables:
    #- group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: WebAPI
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'sp-rg-nonprod-mtp-appsvc-lnx-std-zan-TAPS_Dev'
              appType: 'webAppLinux'
              appName: 'wa-wcg-npoms-nonprod-zan'
              package: '$(Pipeline.Workspace)/WebAPI/WebAPI1.zip'
              runtimeStack: 'DOTNETCORE|6.0'