using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NPOMS.Domain.Dropdown;

namespace NPOMS.Repository.Configurations.Dropdown
{
	public class BranchConfiguration : IEntityTypeConfiguration<Branch>
	{
		public void Configure(EntityTypeBuilder<Branch> builder)
		{
			builder.Property("IsActive").HasDefaultValueSql("1");
			builder.Property("CreatedUserId").HasDefaultValueSql("1");
			builder.Property("CreatedDateTime").HasDefaultValueSql("GetDate()");

			builder.HasData(
				new Branch { Id = 1, Name = "All Branches", BranchCode = null, BankId = 1 },
				new Branch { Id = 2, Name = "Barrydale", BranchCode = null, BankId = 1 },
				new Branch { Id = 3, Name = "Beaufort West", BranchCode = null, BankId = 1 },
				new Branch { Id = 4, Name = "Bellville", BranchCode = null, BankId = 1 },
				new Branch { Id = 5, Name = "Bonnievale", BranchCode = null, BankId = 1 },
				new Branch { Id = 6, Name = "Brackenfell", BranchCode = null, BankId = 1 },
				new Branch { Id = 7, Name = "Bredasdorp", BranchCode = null, BankId = 1 },
				new Branch { Id = 8, Name = "Caledon", BranchCode = null, BankId = 1 },
				new Branch { Id = 9, Name = "Cape Gate", BranchCode = null, BankId = 1 },
				new Branch { Id = 10, Name = "Centurion", BranchCode = null, BankId = 1 },
				new Branch { Id = 11, Name = "Century City", BranchCode = null, BankId = 1 },
				new Branch { Id = 12, Name = "Ceres", BranchCode = null, BankId = 1 },
				new Branch { Id = 13, Name = "Citrusdal", BranchCode = null, BankId = 1 },
				new Branch { Id = 14, Name = "Clanwilliam", BranchCode = null, BankId = 1 },
				new Branch { Id = 15, Name = "Claremont", BranchCode = null, BankId = 1 },
				new Branch { Id = 16, Name = "De Doorns", BranchCode = null, BankId = 1 },
				new Branch { Id = 17, Name = "Durbanville", BranchCode = null, BankId = 1 },
				new Branch { Id = 18, Name = "George", BranchCode = null, BankId = 1 },
				new Branch { Id = 19, Name = "Helderberg", BranchCode = null, BankId = 1 },
				new Branch { Id = 20, Name = "Hermanus", BranchCode = null, BankId = 1 },
				new Branch { Id = 21, Name = "Kenilworth", BranchCode = null, BankId = 1 },
				new Branch { Id = 22, Name = "Kraaifontein", BranchCode = null, BankId = 1 },
				new Branch { Id = 23, Name = "Kuilsriver", BranchCode = null, BankId = 1 },
				new Branch { Id = 24, Name = "Malmesbury", BranchCode = null, BankId = 1 },
				new Branch { Id = 25, Name = "Montagu", BranchCode = null, BankId = 1 },
				new Branch { Id = 26, Name = "Mossel Bay", BranchCode = null, BankId = 1 },
				new Branch { Id = 27, Name = "Mountain Mill", BranchCode = null, BankId = 1 },
				new Branch { Id = 28, Name = "Mowbray", BranchCode = null, BankId = 1 },
				new Branch { Id = 29, Name = "Oudtshoorn", BranchCode = null, BankId = 1 },
				new Branch { Id = 30, Name = "Paarl", BranchCode = null, BankId = 1 },
				new Branch { Id = 31, Name = "Parow", BranchCode = null, BankId = 1 },
				new Branch { Id = 32, Name = "Phillipi", BranchCode = null, BankId = 1 },
				new Branch { Id = 33, Name = "Plein Street", BranchCode = null, BankId = 1 },
				new Branch { Id = 34, Name = "Plettenberg Bay", BranchCode = null, BankId = 1 },
				new Branch { Id = 35, Name = "Porterville", BranchCode = null, BankId = 1 },
				new Branch { Id = 36, Name = "Promenade", BranchCode = null, BankId = 1 },
				new Branch { Id = 37, Name = "Riebeek Road", BranchCode = null, BankId = 1 },
				new Branch { Id = 38, Name = "Riviersonderend", BranchCode = null, BankId = 1 },
				new Branch { Id = 39, Name = "Robertson", BranchCode = null, BankId = 1 },
				new Branch { Id = 40, Name = "Santyger", BranchCode = null, BankId = 1 },
				new Branch { Id = 41, Name = "Somerset mall", BranchCode = null, BankId = 1 },
				new Branch { Id = 42, Name = "Stellenbosch", BranchCode = null, BankId = 1 },
				new Branch { Id = 43, Name = "Strand", BranchCode = null, BankId = 1 },
				new Branch { Id = 44, Name = "Swellendam", BranchCode = null, BankId = 1 },
				new Branch { Id = 45, Name = "Tulbagh", BranchCode = null, BankId = 1 },
				new Branch { Id = 46, Name = "Tyger Manor", BranchCode = null, BankId = 1 },
				new Branch { Id = 47, Name = "Uniondale", BranchCode = null, BankId = 1 },
				new Branch { Id = 48, Name = "Villiersdorp", BranchCode = null, BankId = 1 },
				new Branch { Id = 49, Name = "Vredendal", BranchCode = null, BankId = 1 },
				new Branch { Id = 50, Name = "Wellington", BranchCode = null, BankId = 1 },
				new Branch { Id = 51, Name = "Worcester", BranchCode = null, BankId = 1 },
				new Branch { Id = 52, Name = "Wynberg", BranchCode = null, BankId = 1 },
				new Branch { Id = 53, Name = "Zevenwacht", BranchCode = null, BankId = 1 },
				new Branch { Id = 54, Name = "Athlone", BranchCode = "631309", BankId = 1 },
				new Branch { Id = 55, Name = "Boston Street", BranchCode = "505210", BankId = 1 },
				new Branch { Id = 56, Name = "Durban City", BranchCode = "630126", BankId = 1 },
				new Branch { Id = 57, Name = "Prince Albert", BranchCode = "334708", BankId = 1 },
				new Branch { Id = 58, Name = "Rondebosch", BranchCode = "421109", BankId = 1 },
				new Branch { Id = 59, Name = "Stockenstroom Street", BranchCode = "503107", BankId = 1 },
				new Branch { Id = 60, Name = "Wolseley", BranchCode = "334507", BankId = 1 },
				new Branch { Id = 61, Name = "Knysna", BranchCode = null, BankId = 1 },
				new Branch { Id = 62, Name = "Cape Town Adderley Street", BranchCode = null, BankId = 1 },
				new Branch { Id = 63, Name = "KUILSRIVIER", BranchCode = null, BankId = 1 },
				new Branch { Id = 64, Name = "McTyre Street, Parow", BranchCode = null, BankId = 1 },
				new Branch { Id = 65, Name = "plettenburg", BranchCode = null, BankId = 1 },
				new Branch { Id = 66, Name = "RIEBEECKWEG KUILSRIVIER", BranchCode = null, BankId = 1 },
				new Branch { Id = 67, Name = "SOMERSET WEST", BranchCode = null, BankId = 1 },
				new Branch { Id = 68, Name = "TYGER MALL", BranchCode = null, BankId = 1 },
				new Branch { Id = 69, Name = "ZEVENWACHT MALL", BranchCode = null, BankId = 1 },
				new Branch { Id = 70, Name = "Riversdal", BranchCode = "632005", BankId = 1 },
				new Branch { Id = 71, Name = "Default", BranchCode = "000000", BankId = 1 },
				new Branch { Id = 72, Name = "Bellville", BranchCode = null, BankId = 2 },
				new Branch { Id = 73, Name = "Khayelitsha KBD", BranchCode = null, BankId = 2 },
				new Branch { Id = 74, Name = "Villiersdorp", BranchCode = "200712", BankId = 2 },
				new Branch { Id = 75, Name = "All Branches", BranchCode = null, BankId = 2 },
				new Branch { Id = 76, Name = "Beaufort West", BranchCode = null, BankId = 3 },
				new Branch { Id = 77, Name = "Khayelitsha", BranchCode = null, BankId = 3 },
				new Branch { Id = 78, Name = "Langeberg Mall", BranchCode = null, BankId = 3 },
				new Branch { Id = 79, Name = "Lansdowne", BranchCode = null, BankId = 3 },
				new Branch { Id = 80, Name = "Mossel Bay", BranchCode = null, BankId = 3 },
				new Branch { Id = 81, Name = "N1 City", BranchCode = null, BankId = 3 },
				new Branch { Id = 82, Name = "Paarl", BranchCode = null, BankId = 3 },
				new Branch { Id = 83, Name = "Plumstead", BranchCode = null, BankId = 3 },
				new Branch { Id = 84, Name = "Promenade", BranchCode = null, BankId = 3 },
				new Branch { Id = 85, Name = "Symphony Walk", BranchCode = null, BankId = 3 },
				new Branch { Id = 86, Name = "Vangate Mall", BranchCode = null, BankId = 3 },
				new Branch { Id = 87, Name = "Vineyard", BranchCode = null, BankId = 3 },
				new Branch { Id = 88, Name = "Wellington", BranchCode = null, BankId = 3 },
				new Branch { Id = 89, Name = "Clanwilliam", BranchCode = "200206", BankId = 3 },
				new Branch { Id = 90, Name = "Commercial Account Services", BranchCode = "210554", BankId = 3 },
				new Branch { Id = 91, Name = "Garies", BranchCode = "200406", BankId = 3 },
				new Branch { Id = 92, Name = "Gugulethu", BranchCode = "201409", BankId = 3 },
				new Branch { Id = 93, Name = "Gugulethu Mall", BranchCode = "260557", BankId = 3 },
				new Branch { Id = 94, Name = "Gugulethu Square", BranchCode = "260557", BankId = 3 },
				new Branch { Id = 95, Name = "Heerengracth", BranchCode = "200809", BankId = 3 },
				new Branch { Id = 96, Name = "Heidelberg", BranchCode = "200113", BankId = 3 },
				new Branch { Id = 97, Name = "Helderberg", BranchCode = "271344", BankId = 3 },
				new Branch { Id = 98, Name = "Kenilworth", BranchCode = "200109", BankId = 3 },
				new Branch { Id = 99, Name = "MAIN STREET", BranchCode = "200512", BankId = 3 },
				new Branch { Id = 100, Name = "Maitland", BranchCode = "200209", BankId = 3 },
				new Branch { Id = 101, Name = "Malmesbury", BranchCode = "200507", BankId = 3 },
				new Branch { Id = 102, Name = "Mitchell Plain", BranchCode = "250040", BankId = 3 },
				new Branch { Id = 103, Name = "Montagu", BranchCode = "204709", BankId = 3 },
				new Branch { Id = 104, Name = "Moorreesburg", BranchCode = "200111", BankId = 3 },
				new Branch { Id = 105, Name = "Neelsie", BranchCode = "250937", BankId = 3 },
				new Branch { Id = 106, Name = "Pinelands", BranchCode = "260209", BankId = 3 },
				new Branch { Id = 107, Name = "Sandton Square", BranchCode = "261251", BankId = 3 },
				new Branch { Id = 108, Name = "Sea Point", BranchCode = "201809", BankId = 3 },
				new Branch { Id = 109, Name = "Sedgefield", BranchCode = "210229", BankId = 3 },
				new Branch { Id = 110, Name = "Simons Town", BranchCode = "202309", BankId = 3 },
				new Branch { Id = 111, Name = "Thibault Sqaure", BranchCode = "202509", BankId = 3 },
				new Branch { Id = 112, Name = "Tygerberg", BranchCode = "201410", BankId = 3 },
				new Branch { Id = 113, Name = "Willowbridge", BranchCode = "210655", BankId = 3 },
				new Branch { Id = 114, Name = "York Street", BranchCode = "210114", BankId = 3 },
				new Branch { Id = 115, Name = "Adderley Street", BranchCode = "201409", BankId = 3 },
				new Branch { Id = 116, Name = "All Branches", BranchCode = null, BankId = 3 },
				new Branch { Id = 117, Name = "Athlone", BranchCode = "202409", BankId = 3 },
				new Branch { Id = 118, Name = "Blue Route", BranchCode = "200409", BankId = 3 },
				new Branch { Id = 119, Name = "Caledon", BranchCode = "200212", BankId = 3 },
				new Branch { Id = 120, Name = "Cape Town", BranchCode = "201409", BankId = 3 },
				new Branch { Id = 121, Name = "Ceres", BranchCode = "200107", BankId = 3 },
				new Branch { Id = 122, Name = "Claremont", BranchCode = "200109", BankId = 3 },
				new Branch { Id = 123, Name = "De Doorns", BranchCode = "200207", BankId = 3 },
				new Branch { Id = 124, Name = "Epping", BranchCode = "200810", BankId = 3 },
				new Branch { Id = 125, Name = "Fish Hoek", BranchCode = "202309", BankId = 3 },
				new Branch { Id = 126, Name = "george", BranchCode = "210114", BankId = 3 },
				new Branch { Id = 127, Name = "Grabouw", BranchCode = "200312", BankId = 3 },
				new Branch { Id = 128, Name = "Grassy Park", BranchCode = "203109", BankId = 3 },
				new Branch { Id = 129, Name = "Hermanus", BranchCode = "200412", BankId = 3 },
				new Branch { Id = 130, Name = "Hout Bay", BranchCode = "204009", BankId = 3 },
				new Branch { Id = 131, Name = "Klawer", BranchCode = null, BankId = 3 },
				new Branch { Id = 132, Name = "knysna", BranchCode = "210214", BankId = 3 },
				new Branch { Id = 133, Name = "Kuilsriver", BranchCode = "201110", BankId = 3 },
				new Branch { Id = 134, Name = "Ladismith", BranchCode = "200213", BankId = 3 },
				new Branch { Id = 135, Name = "Makhaza", BranchCode = "210754", BankId = 3 },
				new Branch { Id = 136, Name = "Milnerton", BranchCode = "203309", BankId = 3 },
				new Branch { Id = 137, Name = "Montague Gardens", BranchCode = "204709", BankId = 3 },
				new Branch { Id = 138, Name = "Mowbray", BranchCode = "200309", BankId = 3 },
				new Branch { Id = 139, Name = "Newlands", BranchCode = "202709", BankId = 3 },
				new Branch { Id = 140, Name = "Oudtshoorn", BranchCode = "210414", BankId = 3 },
				new Branch { Id = 141, Name = "Parow", BranchCode = "200510", BankId = 3 },
				new Branch { Id = 142, Name = "Piketberg", BranchCode = "200211", BankId = 3 },
				new Branch { Id = 143, Name = "Plettenberg Bay", BranchCode = "210514", BankId = 3 },
				new Branch { Id = 144, Name = "Robertson", BranchCode = "200413", BankId = 3 },
				new Branch { Id = 145, Name = "Rondebosch", BranchCode = "201509", BankId = 3 },
				new Branch { Id = 146, Name = "Saldanha", BranchCode = "200411", BankId = 3 },
				new Branch { Id = 147, Name = "Somerset mall", BranchCode = "200912", BankId = 3 },
				new Branch { Id = 148, Name = "Stellenbosch", BranchCode = "200610", BankId = 3 },
				new Branch { Id = 149, Name = "Strand", BranchCode = "200612", BankId = 3 },
				new Branch { Id = 150, Name = "Swellendam", BranchCode = "200513", BankId = 3 },
				new Branch { Id = 151, Name = "Table View", BranchCode = "203809", BankId = 3 },
				new Branch { Id = 152, Name = "Thibault Square", BranchCode = "202509", BankId = 3 },
				new Branch { Id = 153, Name = "Tokai", BranchCode = "200409", BankId = 3 },
				new Branch { Id = 154, Name = "Town Centre Mitchell's Plain", BranchCode = "250040", BankId = 3 },
				new Branch { Id = 155, Name = "Tulbagh", BranchCode = "200307", BankId = 3 },
				new Branch { Id = 156, Name = "Tygervalley", BranchCode = "220323", BankId = 3 },
				new Branch { Id = 157, Name = "Villiersdorp", BranchCode = "200712", BankId = 3 },
				new Branch { Id = 158, Name = "Vredenburg", BranchCode = "200311", BankId = 3 },
				new Branch { Id = 159, Name = "Vredendal", BranchCode = "200406", BankId = 3 },
				new Branch { Id = 160, Name = "Woodstock", BranchCode = "201909", BankId = 3 },
				new Branch { Id = 161, Name = "Worcester", BranchCode = "200407", BankId = 3 },
				new Branch { Id = 162, Name = "Wynberg", BranchCode = "202209", BankId = 3 },
				new Branch { Id = 163, Name = "Zevenwacht", BranchCode = "260214", BankId = 3 },
				new Branch { Id = 164, Name = "Town Centre", BranchCode = null, BankId = 3 },
				new Branch { Id = 165, Name = "Durbanville", BranchCode = null, BankId = 3 },
				new Branch { Id = 166, Name = "250555", BranchCode = null, BankId = 3 },
				new Branch { Id = 167, Name = "Adderley Str. Cape Town", BranchCode = null, BankId = 3 },
				new Branch { Id = 168, Name = "Adderley Street Cape Town", BranchCode = null, BankId = 3 },
				new Branch { Id = 169, Name = "Adderley Street, Cape Town", BranchCode = null, BankId = 3 },
				new Branch { Id = 170, Name = "Adderley Street,Cape Town", BranchCode = null, BankId = 3 },
				new Branch { Id = 171, Name = "ADDERLY STREET", BranchCode = null, BankId = 3 },
				new Branch { Id = 172, Name = "BLUE ROUTE MALL", BranchCode = null, BankId = 3 },
				new Branch { Id = 173, Name = "BLUE ROUTE TOKAI", BranchCode = null, BankId = 3 },
				new Branch { Id = 174, Name = "EPPINDUST", BranchCode = null, BankId = 3 },
				new Branch { Id = 175, Name = "EPPINGDUST", BranchCode = null, BankId = 3 },
				new Branch { Id = 176, Name = "Eppingindust", BranchCode = null, BankId = 3 },
				new Branch { Id = 177, Name = "GRASSY PARK CAPE TOWN", BranchCode = null, BankId = 3 },
				new Branch { Id = 178, Name = "Grassy Park, Cape Town", BranchCode = null, BankId = 3 },
				new Branch { Id = 179, Name = "KLAWER SERVICE BRANCHE", BranchCode = null, BankId = 3 },
				new Branch { Id = 180, Name = "Kuilsrivier", BranchCode = null, BankId = 3 },
				new Branch { Id = 181, Name = "ladiesmith", BranchCode = null, BankId = 3 },
				new Branch { Id = 182, Name = "Makhaza Shopping Centre", BranchCode = null, BankId = 3 },
				new Branch { Id = 183, Name = "Mlnerton", BranchCode = null, BankId = 3 },
				new Branch { Id = 184, Name = "Mobray", BranchCode = null, BankId = 3 },
				new Branch { Id = 185, Name = "montague", BranchCode = null, BankId = 3 },
				new Branch { Id = 186, Name = "Mosselbay", BranchCode = null, BankId = 3 },
				new Branch { Id = 187, Name = "PAROW 002", BranchCode = null, BankId = 3 },
				new Branch { Id = 188, Name = "SALDAHNA", BranchCode = null, BankId = 3 },
				new Branch { Id = 189, Name = "SANDTON", BranchCode = null, BankId = 3 },
				new Branch { Id = 190, Name = "SANDTON SQUARE CRAIGHALL", BranchCode = null, BankId = 3 },
				new Branch { Id = 191, Name = "SOMERSET WEST", BranchCode = null, BankId = 3 },
				new Branch { Id = 192, Name = "Somerset West Mall", BranchCode = null, BankId = 3 },
				new Branch { Id = 193, Name = "Stellenbosch C.P", BranchCode = null, BankId = 3 },
				new Branch { Id = 194, Name = "Symphony", BranchCode = null, BankId = 3 },
				new Branch { Id = 195, Name = "TYGERVALIE", BranchCode = null, BankId = 3 },
				new Branch { Id = 196, Name = "VANGATE", BranchCode = null, BankId = 3 },
				new Branch { Id = 197, Name = "Vangate Mall Athlone", BranchCode = null, BankId = 3 },
				new Branch { Id = 198, Name = "VILLIERSDORD", BranchCode = null, BankId = 3 },
				new Branch { Id = 199, Name = "villierssdorp", BranchCode = null, BankId = 3 },
				new Branch { Id = 200, Name = "Zevenwacht Mall", BranchCode = null, BankId = 3 },
				new Branch { Id = 201, Name = "Ceres", BranchCode = null, BankId = 4 },
				new Branch { Id = 202, Name = "Avonwood", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 203, Name = "Beaufort West", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 204, Name = "Bellville East", BranchCode = "103210", BankId = 4 },
				new Branch { Id = 205, Name = "Brackenfell", BranchCode = "103310", BankId = 4 },
				new Branch { Id = 206, Name = "BUSINESS WINELANDS", BranchCode = "149821", BankId = 4 },
				new Branch { Id = 207, Name = "Cape Commercial", BranchCode = "441010", BankId = 4 },
				new Branch { Id = 208, Name = "Cavendish Square", BranchCode = "145209", BankId = 4 },
				new Branch { Id = 209, Name = "Franschhoek", BranchCode = "167005", BankId = 4 },
				new Branch { Id = 210, Name = "Gardens", BranchCode = "101009", BankId = 4 },
				new Branch { Id = 211, Name = "Gardens Centre", BranchCode = "100909", BankId = 4 },
				new Branch { Id = 212, Name = "GRAHAMSTOWN", BranchCode = "122005", BankId = 4 },
				new Branch { Id = 213, Name = "Heerengracht", BranchCode = "103109", BankId = 4 },
				new Branch { Id = 214, Name = "Helderberg Commercial", BranchCode = "441012", BankId = 4 },
				new Branch { Id = 215, Name = "Inland Garden Route Paarl", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 216, Name = "Kenilworth", BranchCode = "198760", BankId = 4 },
				new Branch { Id = 217, Name = "Khayaelitsha Mall", BranchCode = "172305", BankId = 4 },
				new Branch { Id = 218, Name = "Makhaza", BranchCode = "155405", BankId = 4 },
				new Branch { Id = 219, Name = "Mbekweni", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 220, Name = "Mitchell Plain", BranchCode = "107909", BankId = 4 },
				new Branch { Id = 221, Name = "Montague Gardens", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 222, Name = "Moorreesburg", BranchCode = "128505", BankId = 4 },
				new Branch { Id = 223, Name = "Nomzamo", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 224, Name = "Northern Peninsula", BranchCode = "118602", BankId = 4 },
				new Branch { Id = 225, Name = "Paarl Mall", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 226, Name = "Peoples Athlone", BranchCode = "115909", BankId = 4 },
				new Branch { Id = 227, Name = "Promenade", BranchCode = "107909", BankId = 4 },
				new Branch { Id = 228, Name = "Robertson", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 229, Name = "Sea Point", BranchCode = "106909", BankId = 4 },
				new Branch { Id = 230, Name = "Southern Peninsula", BranchCode = "123209", BankId = 4 },
				new Branch { Id = 231, Name = "Stilbaai", BranchCode = "184705", BankId = 4 },
				new Branch { Id = 232, Name = "Swartland", BranchCode = "128505", BankId = 4 },
				new Branch { Id = 233, Name = "The Bridge", BranchCode = "118602", BankId = 4 },
				new Branch { Id = 234, Name = "Tokai", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 235, Name = "Tygervalley", BranchCode = "103910", BankId = 4 },
				new Branch { Id = 236, Name = "Vredenburg", BranchCode = "128505", BankId = 4 },
				new Branch { Id = 237, Name = "Vredendal", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 238, Name = "Wellington", BranchCode = "102905", BankId = 4 },
				new Branch { Id = 239, Name = "All Branches", BranchCode = null, BankId = 4 },
				new Branch { Id = 240, Name = "Atlantis", BranchCode = "193765", BankId = 4 },
				new Branch { Id = 241, Name = "Belhar", BranchCode = "120405", BankId = 4 },
				new Branch { Id = 242, Name = "Bellville", BranchCode = "108110", BankId = 4 },
				new Branch { Id = 243, Name = "Bredasdorp", BranchCode = "125142", BankId = 4 },
				new Branch { Id = 244, Name = "Caledon", BranchCode = "196005", BankId = 4 },
				new Branch { Id = 245, Name = "Cape Town", BranchCode = "100909", BankId = 4 },
				new Branch { Id = 246, Name = "Cape Town Station", BranchCode = "100989", BankId = 4 },
				new Branch { Id = 247, Name = "Clanwilliam", BranchCode = "153305", BankId = 4 },
				new Branch { Id = 248, Name = "Claremont", BranchCode = "104609", BankId = 4 },
				new Branch { Id = 249, Name = "Constantia", BranchCode = "101109", BankId = 4 },
				new Branch { Id = 250, Name = "Durbanville", BranchCode = "103710", BankId = 4 },
				new Branch { Id = 251, Name = "Garden Route", BranchCode = "153614", BankId = 4 },
				new Branch { Id = 252, Name = "Garden Route Mall", BranchCode = "198765", BankId = 4 },
				new Branch { Id = 253, Name = "George", BranchCode = "109114", BankId = 4 },
				new Branch { Id = 254, Name = "Hermanus", BranchCode = "134512", BankId = 4 },
				new Branch { Id = 255, Name = "Inland Garden Route", BranchCode = "187505", BankId = 4 },
				new Branch { Id = 256, Name = "Khayelitsha", BranchCode = "172305", BankId = 4 },
				new Branch { Id = 257, Name = "Khayelitsha Mall", BranchCode = "172305", BankId = 4 },
				new Branch { Id = 258, Name = "Knysna", BranchCode = "108914", BankId = 4 },
				new Branch { Id = 259, Name = "Kraaifontein", BranchCode = "112305", BankId = 4 },
				new Branch { Id = 260, Name = "Kuilsriver", BranchCode = "115310", BankId = 4 },
				new Branch { Id = 261, Name = "Malmesbury", BranchCode = "154605", BankId = 4 },
				new Branch { Id = 262, Name = "Mitchells Plain", BranchCode = "144905", BankId = 4 },
				new Branch { Id = 263, Name = "Mitchell's Plain", BranchCode = "144905", BankId = 4 },
				new Branch { Id = 264, Name = "Mossel Bay", BranchCode = "168905", BankId = 4 },
				new Branch { Id = 265, Name = "Nonqubela", BranchCode = "110634", BankId = 4 },
				new Branch { Id = 266, Name = "Oudtshoorn", BranchCode = "175205", BankId = 4 },
				new Branch { Id = 267, Name = "Paarl", BranchCode = "102210", BankId = 4 },
				new Branch { Id = 268, Name = "Paarl Lady Grey St", BranchCode = "114810", BankId = 4 },
				new Branch { Id = 269, Name = "Parow", BranchCode = "102510", BankId = 4 },
				new Branch { Id = 270, Name = "Phillipi", BranchCode = "107510", BankId = 4 },
				new Branch { Id = 271, Name = "Pinelands", BranchCode = "104709", BankId = 4 },
				new Branch { Id = 272, Name = "Promenade Mall", BranchCode = "107909", BankId = 4 },
				new Branch { Id = 273, Name = "Riversdal", BranchCode = "162645", BankId = 4 },
				new Branch { Id = 274, Name = "Rondebosch", BranchCode = "104809", BankId = 4 },
				new Branch { Id = 275, Name = "Somerset mall", BranchCode = "114145", BankId = 4 },
				new Branch { Id = 276, Name = "Stellenbosch", BranchCode = "107110", BankId = 4 },
				new Branch { Id = 277, Name = "Swellendam", BranchCode = "132105", BankId = 4 },
				new Branch { Id = 278, Name = "Town Centre", BranchCode = "144905", BankId = 4 },
				new Branch { Id = 279, Name = "Tygerberg", BranchCode = "118602", BankId = 4 },
				new Branch { Id = 280, Name = "Winelands Stellenbosch", BranchCode = "149821", BankId = 4 },
				new Branch { Id = 281, Name = "Worcester", BranchCode = "101507", BankId = 4 },
				new Branch { Id = 282, Name = "York Street", BranchCode = "109114", BankId = 4 },
				new Branch { Id = 283, Name = "Zomelust Estate Paarl", BranchCode = "147005", BankId = 4 },
				new Branch { Id = 284, Name = "147005", BranchCode = null, BankId = 4 },
				new Branch { Id = 285, Name = "ANTIANTIC", BranchCode = null, BankId = 4 },
				new Branch { Id = 286, Name = "ANTLANTIS", BranchCode = null, BankId = 4 },
				new Branch { Id = 287, Name = "Beaufort - West", BranchCode = null, BankId = 4 },
				new Branch { Id = 288, Name = "Bellville CBD", BranchCode = null, BankId = 4 },
				new Branch { Id = 289, Name = "BELLVILLE CDB", BranchCode = null, BankId = 4 },
				new Branch { Id = 290, Name = "caldeon", BranchCode = null, BankId = 4 },
				new Branch { Id = 291, Name = "CAVENDISH", BranchCode = null, BankId = 4 },
				new Branch { Id = 292, Name = "CHURCH SQUARE  KUILS RIVIER", BranchCode = null, BankId = 4 },
				new Branch { Id = 293, Name = "HELDERBERG KOMMERSIELE", BranchCode = null, BankId = 4 },
				new Branch { Id = 294, Name = "KAAP KOMMERSIEEL", BranchCode = null, BankId = 4 },
				new Branch { Id = 295, Name = "KUILSRIVIER", BranchCode = null, BankId = 4 },
				new Branch { Id = 296, Name = "Mitchells Plain Town Centre", BranchCode = null, BankId = 4 },
				new Branch { Id = 297, Name = "Mitchell's Plain, Promenade Mall", BranchCode = null, BankId = 4 },
				new Branch { Id = 298, Name = "Montaque Gardens", BranchCode = null, BankId = 4 },
				new Branch { Id = 299, Name = "Mosselbay", BranchCode = null, BankId = 4 },
				new Branch { Id = 300, Name = "PROMINADE", BranchCode = null, BankId = 4 },
				new Branch { Id = 301, Name = "Seapoint", BranchCode = null, BankId = 4 },
				new Branch { Id = 302, Name = "Somerset", BranchCode = null, BankId = 4 },
				new Branch { Id = 303, Name = "Somerset Wesr", BranchCode = null, BankId = 4 },
				new Branch { Id = 304, Name = "SOMERSET WEST", BranchCode = null, BankId = 4 },
				new Branch { Id = 305, Name = "TYGERBERG WINELANDS", BranchCode = null, BankId = 4 },
				new Branch { Id = 306, Name = "Winelands", BranchCode = null, BankId = 4 },
				new Branch { Id = 307, Name = "grabouw", BranchCode = "50212", BankId = 4 },
				new Branch { Id = 308, Name = "Athlone", BranchCode = "26609", BankId = 5 },
				new Branch { Id = 309, Name = "Bayside", BranchCode = "51001", BankId = 5 },
				new Branch { Id = 310, Name = "Braamfontein", BranchCode = "4805", BankId = 5 },
				new Branch { Id = 311, Name = "Brackenfell", BranchCode = "30310", BankId = 5 },
				new Branch { Id = 312, Name = "Citrusdal", BranchCode = "50011", BankId = 5 },
				new Branch { Id = 313, Name = "Clanwilliam", BranchCode = "50106", BankId = 5 },
				new Branch { Id = 314, Name = "Goodwood", BranchCode = "31010", BankId = 5 },
				new Branch { Id = 315, Name = "Lainsburg", BranchCode = "51108", BankId = 5 },
				new Branch { Id = 316, Name = "LYNNWOOD RIDGE", BranchCode = "51001", BankId = 5 },
				new Branch { Id = 317, Name = "Mellville", BranchCode = "6105", BankId = 5 },
				new Branch { Id = 318, Name = "Northcliff", BranchCode = "6305", BankId = 5 },
				new Branch { Id = 319, Name = "Parow West", BranchCode = "51001", BankId = 5 },
				new Branch { Id = 320, Name = "Plumstead", BranchCode = "25309", BankId = 5 },
				new Branch { Id = 321, Name = "Rondeboch", BranchCode = "25009", BankId = 5 },
				new Branch { Id = 322, Name = "Sea Point", BranchCode = "24109", BankId = 5 },
				new Branch { Id = 323, Name = "Strand", BranchCode = "33112", BankId = 5 },
				new Branch { Id = 324, Name = "Thembalethu George", BranchCode = "51001", BankId = 5 },
				new Branch { Id = 325, Name = "Thibault Sqaure", BranchCode = "20909", BankId = 5 },
				new Branch { Id = 326, Name = "Tulbagh", BranchCode = "50307", BankId = 5 },
				new Branch { Id = 327, Name = "All Branches", BranchCode = null, BankId = 5 },
				new Branch { Id = 328, Name = "Beaufort West", BranchCode = "50008", BankId = 5 },
				new Branch { Id = 329, Name = "Bellville", BranchCode = "51001", BankId = 5 },
				new Branch { Id = 330, Name = "Blue Route", BranchCode = "25609", BankId = 5 },
				new Branch { Id = 331, Name = "Caledon", BranchCode = "50112", BankId = 5 },
				new Branch { Id = 332, Name = "Calitzdorp", BranchCode = "50014", BankId = 5 },
				new Branch { Id = 333, Name = "Cape Gate", BranchCode = "23910", BankId = 5 },
				new Branch { Id = 334, Name = "Cape Town", BranchCode = "20009", BankId = 5 },
				new Branch { Id = 335, Name = "Ceres", BranchCode = "50007", BankId = 5 },
				new Branch { Id = 336, Name = "Claremont", BranchCode = "25109", BankId = 5 },
				new Branch { Id = 337, Name = "Constantia", BranchCode = "25309", BankId = 5 },
				new Branch { Id = 338, Name = "Darling", BranchCode = "50111", BankId = 5 },
				new Branch { Id = 339, Name = "De Doorns", BranchCode = "50107", BankId = 5 },
				new Branch { Id = 340, Name = "De rust", BranchCode = "50114", BankId = 5 },
				new Branch { Id = 341, Name = "Fish Hoek", BranchCode = "36009", BankId = 5 },
				new Branch { Id = 342, Name = "Gatesville", BranchCode = "25909", BankId = 5 },
				new Branch { Id = 343, Name = "George", BranchCode = "50214", BankId = 5 },
				new Branch { Id = 344, Name = "Grabouw", BranchCode = "50212", BankId = 5 },
				new Branch { Id = 345, Name = "Helderberg", BranchCode = "33012", BankId = 5 },
				new Branch { Id = 346, Name = "Hermanus", BranchCode = "50312", BankId = 5 },
				new Branch { Id = 347, Name = "Khayelitsha", BranchCode = "25909", BankId = 5 },
				new Branch { Id = 348, Name = "Knysna", BranchCode = "50314", BankId = 5 },
				new Branch { Id = 349, Name = "Kromboom", BranchCode = "26209", BankId = 5 },
				new Branch { Id = 350, Name = "Laaiplek", BranchCode = "50611", BankId = 5 },
				new Branch { Id = 351, Name = "Ladismith", BranchCode = "50113", BankId = 5 },
				new Branch { Id = 352, Name = "Lamberts Bay", BranchCode = "50206", BankId = 5 },
				new Branch { Id = 353, Name = "Malmesbury", BranchCode = "50507", BankId = 5 },
				new Branch { Id = 354, Name = "Milnerton", BranchCode = "26509", BankId = 5 },
				new Branch { Id = 355, Name = "Montagu", BranchCode = "50213", BankId = 5 },
				new Branch { Id = 356, Name = "Mossel Bay", BranchCode = "50414", BankId = 5 },
				new Branch { Id = 357, Name = "Mowbray", BranchCode = "24909", BankId = 5 },
				new Branch { Id = 358, Name = "Oudtshoorn", BranchCode = "50514", BankId = 5 },
				new Branch { Id = 359, Name = "Paarl", BranchCode = "50210", BankId = 5 },
				new Branch { Id = 360, Name = "Parow", BranchCode = "31110", BankId = 5 },
				new Branch { Id = 361, Name = "Piketberg", BranchCode = "50411", BankId = 5 },
				new Branch { Id = 362, Name = "Pinelands", BranchCode = "36309", BankId = 5 },
				new Branch { Id = 363, Name = "Plettenberg Bay", BranchCode = "50714", BankId = 5 },
				new Branch { Id = 364, Name = "Porterville", BranchCode = "50207", BankId = 5 },
				new Branch { Id = 365, Name = "Promenade", BranchCode = "26609", BankId = 5 },
				new Branch { Id = 366, Name = "Robertson", BranchCode = "50413", BankId = 5 },
				new Branch { Id = 367, Name = "Rondebosch", BranchCode = "25009", BankId = 5 },
				new Branch { Id = 368, Name = "Somerset mall", BranchCode = "33012", BankId = 5 },
				new Branch { Id = 369, Name = "Stellenbosch", BranchCode = "50610", BankId = 5 },
				new Branch { Id = 370, Name = "Swellendam", BranchCode = "50513", BankId = 5 },
				new Branch { Id = 371, Name = "Thibault Square", BranchCode = "102510", BankId = 5 },
				new Branch { Id = 372, Name = "Tyger Manor", BranchCode = "50410", BankId = 5 },
				new Branch { Id = 373, Name = "Uniondale", BranchCode = "50215", BankId = 5 },
				new Branch { Id = 374, Name = "Vangate Mall", BranchCode = "25909", BankId = 5 },
				new Branch { Id = 375, Name = "Vredenburg", BranchCode = "50511", BankId = 5 },
				new Branch { Id = 376, Name = "Vredendal", BranchCode = "50706", BankId = 5 },
				new Branch { Id = 377, Name = "Wellington", BranchCode = "50710", BankId = 5 },
				new Branch { Id = 378, Name = "Worcester", BranchCode = "50407", BankId = 5 },
				new Branch { Id = 379, Name = "Wynberg", BranchCode = "25309", BankId = 5 },
				new Branch { Id = 380, Name = "Beaufort- West", BranchCode = null, BankId = 5 },
				new Branch { Id = 381, Name = "Blue Route Centre", BranchCode = null, BankId = 5 },
				new Branch { Id = 382, Name = "BLUE ROUTE MALL, TOKAI", BranchCode = null, BankId = 5 },
				new Branch { Id = 383, Name = "Hyde Park", BranchCode = null, BankId = 5 },
				new Branch { Id = 384, Name = "Johannesburg", BranchCode = null, BankId = 5 },
				new Branch { Id = 385, Name = "Kroomboom", BranchCode = null, BankId = 5 },
				new Branch { Id = 386, Name = "LAMBERSBAAI", BranchCode = null, BankId = 5 },
				new Branch { Id = 387, Name = "LAMBERTSBAAI", BranchCode = null, BankId = 5 },
				new Branch { Id = 388, Name = "Lambertsbay", BranchCode = null, BankId = 5 },
				new Branch { Id = 389, Name = "MISGUND", BranchCode = null, BankId = 5 },
				new Branch { Id = 390, Name = "Mobray", BranchCode = null, BankId = 5 },
				new Branch { Id = 391, Name = "Mosselbaai", BranchCode = null, BankId = 5 },
				new Branch { Id = 392, Name = "Mosselbay", BranchCode = null, BankId = 5 },
				new Branch { Id = 393, Name = "Mowbray Cape Town", BranchCode = null, BankId = 5 },
				new Branch { Id = 394, Name = "Parow centre", BranchCode = null, BankId = 5 },
				new Branch { Id = 395, Name = "PORTVILLE", BranchCode = null, BankId = 5 },
				new Branch { Id = 396, Name = "Promenade 1", BranchCode = null, BankId = 5 },
				new Branch { Id = 397, Name = "Prominade", BranchCode = null, BankId = 5 },
				new Branch { Id = 398, Name = "PROMINADE 1", BranchCode = null, BankId = 5 },
				new Branch { Id = 399, Name = "Somerset West", BranchCode = null, BankId = 5 },
				new Branch { Id = 400, Name = "Thibaullt Square", BranchCode = null, BankId = 5 },
				new Branch { Id = 401, Name = "Tygar Manor", BranchCode = null, BankId = 5 },
				new Branch { Id = 402, Name = "TYGER MINOR", BranchCode = null, BankId = 5 },
				new Branch { Id = 403, Name = "tyger minor duplicate", BranchCode = null, BankId = 5 },
				new Branch { Id = 404, Name = "TYGERMINOR", BranchCode = null, BankId = 5 },
				new Branch { Id = 405, Name = "TYGOR MINOR", BranchCode = null, BankId = 5 },
				new Branch { Id = 406, Name = "Universal Code", BranchCode = null, BankId = 5 },
				new Branch { Id = 407, Name = "Van Rhynsdorp", BranchCode = null, BankId = 5 },
				new Branch { Id = 408, Name = "VANGATE", BranchCode = null, BankId = 5 },
				new Branch { Id = 409, Name = "Walvis Bay", BranchCode = null, BankId = 6 },
				new Branch { Id = 410, Name = "All Branches", BranchCode = null, BankId = 6 },
				new Branch { Id = 411, Name = "Cape Town", BranchCode = "450109", BankId = 7 },
				new Branch { Id = 412, Name = "Oudtshoorn", BranchCode = "198765", BankId = 7 },
				new Branch { Id = 413, Name = "All Branches", BranchCode = null, BankId = 7 },
				new Branch { Id = 414, Name = "Bloemfontein", BranchCode = null, BankId = 8 },
				new Branch { Id = 415, Name = "LANGA", BranchCode = null, BankId = 8 },
				new Branch { Id = 416, Name = "Phillipi Post Office", BranchCode = null, BankId = 8 },
				new Branch { Id = 417, Name = "Kromboom", BranchCode = "26209", BankId = 8 },
				new Branch { Id = 418, Name = "Oudtshoorn", BranchCode = "51001", BankId = 8 },
				new Branch { Id = 419, Name = "All Branches", BranchCode = null, BankId = 8 },
				new Branch { Id = 420, Name = "Kroomboom", BranchCode = null, BankId = 8 },
				new Branch { Id = 421, Name = "Default", BranchCode = "000000", BankId = 9 }
			);
		}
	}
}
