using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NPOMS.Domain.Lookup;

namespace NPOMS.Repository.Configurations.Lookup
{
	public class ActivityListConfiguration : IEntityTypeConfiguration<ActivityList>
	{
		public void Configure(EntityTypeBuilder<ActivityList> builder)
		{
			builder.Property("IsActive").HasDefaultValueSql("1");
			builder.Property("CreatedUserId").HasDefaultValueSql("1");
			builder.Property("CreatedDateTime").HasDefaultValueSql("GetDate()");

			builder.HasData(
				new ActivityList { Id = 1, Name = "Quarterly reports", Description = "Quarterly reports" },
				new ActivityList { Id = 2, Name = "Quarterly stakeholder engagements", Description = "Quarterly stakeholder engagements" },
				new ActivityList { Id = 3, Name = "Provision of resources", Description = "Provision of resources" },
				new ActivityList { Id = 4, Name = "Capacity Development", Description = "Capacity Development" },
				new ActivityList { Id = 5, Name = "Monitoring and Evaluation", Description = "Monitoring and Evaluation" },
				new ActivityList { Id = 6, Name = "Quality Improvement", Description = "Quality Improvement" },
				new ActivityList { Id = 7, Name = "Implementation of Human Rights activities", Description = "Implementation of Human Rights activities" },
				new ActivityList { Id = 8, Name = "Advocacy", Description = "Advocacy" },
				new ActivityList { Id = 9, Name = "GP referrals", Description = "GP referrals" },
				new ActivityList { Id = 10, Name = "Engagement with taxi industry", Description = "Engagement with taxi industry" },
				new ActivityList { Id = 11, Name = "Awareness campaigns", Description = "Awareness campaigns" },
				new ActivityList { Id = 12, Name = "HIV Testing", Description = "HIV Testing" },
				new ActivityList { Id = 13, Name = "Health Screening", Description = "Health Screening" },
				new ActivityList { Id = 14, Name = "Introduction of self-screening", Description = "Introduction of self-screening" },
				new ActivityList { Id = 15, Name = "Reduce Stima & Discrimination", Description = "Reduce Stima & Discrimination" },
				new ActivityList { Id = 16, Name = "Provide Legal Support", Description = "Provide Legal Support" },
				new ActivityList { Id = 17, Name = "Distribution of posters, leaflets and pamphlets", Description = "Distribution of posters, leaflets and pamphlets" },
				new ActivityList { Id = 18, Name = "Advocacy for PWID", Description = "Advocacy for People Who use and inject Drugs (PWID)" },
				new ActivityList { Id = 19, Name = "Decriminalisation of Sex Work ", Description = "Decriminalisation of Sex Work " },
				new ActivityList { Id = 20, Name = "Sesitization engagements", Description = "Sesitization engagements" },
				new ActivityList { Id = 21, Name = "Mapping", Description = "Mapping" },
				new ActivityList { Id = 22, Name = "Providing CBM toolkits", Description = "Providing CBM toolkits" },
				new ActivityList { Id = 23, Name = "Distribute IEC material", Description = "Distribute IEC material" },
				new ActivityList { Id = 24, Name = "Training", Description = "Training" },
				new ActivityList { Id = 25, Name = "Demand creation", Description = "Demand creation" },
				new ActivityList { Id = 26, Name = "Score card development and monitoring", Description = "Score card development and monitoring" },
				new ActivityList { Id = 27, Name = "Skills development", Description = "Skills development" },
				new ActivityList { Id = 28, Name = "Obtain facility start-up kits from NDOH", Description = "Obtain facility start-up kits from NDOH" },
				new ActivityList { Id = 29, Name = "Facility and site assessments", Description = "Facility and site assessments" },
				new ActivityList { Id = 30, Name = "Develop assessment tools", Description = "Develop assessment tools" },
				new ActivityList { Id = 31, Name = "SOP development", Description = "SOP development" },
				new ActivityList { Id = 32, Name = "Deploy NDOH tools", Description = "Deploy NDOH tools" },
				new ActivityList { Id = 33, Name = "Deploy NDOH tools and Tier.net modules", Description = "Deploy NDOH tools and Tier.net module to all identified sites" },
				new ActivityList { Id = 34, Name = "Update PrEP finder on NDOH website", Description = "Update PrEP finder on NDOH website to include facilities" },
				new ActivityList { Id = 35, Name = "Data quality assessment", Description = "Data quality assessment" },
				new ActivityList { Id = 36, Name = "Facility-level data review", Description = "Facility-level data review" },
				new ActivityList { Id = 37, Name = "Conduct  performance management activities", Description = "Conduct  performance management activities" },
				new ActivityList { Id = 38, Name = "Distribution of MINA collateral, posters and IEC", Description = "Distribution of MINA collateral, posters an IEC to facilities." },
				new ActivityList { Id = 39, Name = "Facilitate the branding in facilities", Description = "Facilitate the branding in facilities" },
				new ActivityList { Id = 40, Name = "Identification of MINA champion", Description = "Identification of MINA champion /facility in conjunction with facility manager" },
				new ActivityList { Id = 41, Name = "Advocacy for mesn health", Description = "Advocacy for mesn health" },
				new ActivityList { Id = 42, Name = "HiV prevention", Description = "HiV prevention" },
				new ActivityList { Id = 43, Name = "HTS", Description = "HTS" },
				new ActivityList { Id = 44, Name = "Care", Description = "Care" },
				new ActivityList { Id = 45, Name = "Treatment/FP Services", Description = "Treatment/FP Services" },
				new ActivityList { Id = 46, Name = "DREAMS stakeholder engagement", Description = "DREAMS stakeholder engagement" },
				new ActivityList { Id = 47, Name = "DREAMS Ambassador development", Description = "DREAMS Ambassador development" },
				new ActivityList { Id = 48, Name = "Support the establishment of AYFS", Description = "Support the establishment of facility and sub-district Adolescent and Youth Friendly Services (AYFS)" },
				new ActivityList { Id = 49, Name = "Promote provision of integrated services to AGYW", Description = "Promote provision of integrated HTS/HIV Prevention/FP/SRH services to AGYW at FP units or youth care corners" },
				new ActivityList { Id = 50, Name = "Guideline development", Description = "Guideline development" },
				new ActivityList { Id = 51, Name = "LIVES Training", Description = "LIVES Training" },
				new ActivityList { Id = 52, Name = "Avial adolescent clinics and youth corners", Description = "Avial adolescent clinics and youth corners" },
				new ActivityList { Id = 53, Name = "Mentorship on client engagement", Description = "Mentorship on client engagement" },
				new ActivityList { Id = 54, Name = "Implement PrEP services", Description = "Implement PrEP services" },
				new ActivityList { Id = 55, Name = "Welcome back campaign", Description = "Welcome back campaign" },
				new ActivityList { Id = 56, Name = "Stakeholder enagement", Description = "Stakeholder enagement" },
				new ActivityList { Id = 57, Name = "Site visits and assesssments", Description = "Site visits and assesssments" },
				new ActivityList { Id = 58, Name = "Support policy development", Description = "Support policy development" },
				new ActivityList { Id = 59, Name = "Ensure pregnant women are started same day    ", Description = "Ensure that 90 % of pregnant women are started same day    " },
				new ActivityList { Id = 60, Name = "IQC of HIV Test kits", Description = "IQC of HIV Test kits" },
				new ActivityList { Id = 61, Name = "Rapid test quality improvements", Description = "Rapid test quality improvements" },
				new ActivityList { Id = 62, Name = "Conduct 6 monthly SPI -RT assessments", Description = "Support and Conduct 6 monthly SPI -RT assessments in all facilities" },
				new ActivityList { Id = 63, Name = "Quality Assessments", Description = "Quality Assessments" },
				new ActivityList { Id = 64, Name = "Conduct monthly TB register audits", Description = "Conduct monthly TB register audits to identify gaps in HIV testing" },
				new ActivityList { Id = 65, Name = "Review presumptive TB register", Description = "Review presumptive TB register to indentify confirmed Tb + clients not initiated on ART and fasttrack for initiation" },
				new ActivityList { Id = 66, Name = "Analyse IPT Data to improve completion of IPT", Description = "Analyse IPT Data to improve initiation and completion of IPT" },
				new ActivityList { Id = 67, Name = "Conduct monthly PMTCT register reviews", Description = "Conduct monthly PMTCT register reviews" },
				new ActivityList { Id = 68, Name = "Funder prescribed assessments", Description = "Funder prescribed assessments" },
				new ActivityList { Id = 69, Name = "Conduct routine clinical chart and register review", Description = "Conduct routine clinical chart and register reviews to identify gaps in HTS/HIV/TB services" },
				new ActivityList { Id = 70, Name = "Develop facility QIPs", Description = "Develop facility QIPs in conjunction with facility team  according to the gaps identified" },
				new ActivityList { Id = 71, Name = "Monitor implementation of facility QIPs", Description = "Monitor implementation of facility QIPs" },
				new ActivityList { Id = 72, Name = "Provide coaching and upskilling", Description = "Provide coaching  and upskilling in implementation and monitoring of improvement activities (FIP's and QIP's) to facility staff" },
				new ActivityList { Id = 73, Name = "Support the implementation of TB screening", Description = "Support the implementation of TB screening for all ART clients at every visit and actioning for TPT or TB testing in supported facilities" },
				new ActivityList { Id = 74, Name = "Monthly reviews of TB screening practices", Description = "Monthly reviews of facility TB screening practices among ART clients flagging for low TPT uptake and <90% screening of all visiting ART clients" },
				new ActivityList { Id = 75, Name = "Monthly review of Presumptive register", Description = "Monthly review of Presumptive  register to ensure all Presumptive clients have an HIV and or ART status, clients not initiated on ART and fast track  for initiation." },
				new ActivityList { Id = 76, Name = "Assist with training staff on HTS", Description = "Assist with training staff on HTS and ART for Presumptive TB" },
				new ActivityList { Id = 77, Name = "Assist with training of staff on TPT", Description = "Assist with training of staff  on TPT guidelines and management of TPT in ART clients" },
				new ActivityList { Id = 78, Name = "Monthly review of facility TPT to ART", Description = "Monthly review of facility TPT to ART initiation rates to ensure above 85%" },
				new ActivityList { Id = 79, Name = "Monthly review of facility missed opportunities", Description = "Monthly review of facility missed opportunities to initiate TPT in TX_NEW 3 months prior and flag for reassessment of TPT eligibility and TPT initiation" },
				new ActivityList { Id = 80, Name = "Monthly review of facility TPT outcomes", Description = "Monthly review of facility TPT outcomes of clients initiated 12 months prior flagging all patients with outstanding TPT outcomes, ensure outcomes are completed." },
				new ActivityList { Id = 81, Name = "Strengthening of results management", Description = "Strengthening of results management" },
				new ActivityList { Id = 82, Name = "Monthly review of specimen rejection rates", Description = "Monthly review of specimen rejection rates for   CD4/VL/PCR/TB GenxPert and implement corrective measures    on rejections caused by pre-analytical errors." },
				new ActivityList { Id = 83, Name = "Support with implementation of Post Natal Clubs", Description = "Support with the roll out and implementation of Post Natal Clubs" },
				new ActivityList { Id = 84, Name = "Provide support on Post Natal Clubs", Description = "Provide oversight support on Post Natal Clubs(coaching of PNC Nurses)" },
				new ActivityList { Id = 85, Name = "Conduct PMTCT register review to monitor", Description = "Conduct PMTCT register review to monitor" },
				new ActivityList { Id = 86, Name = "Coaching on correct completion of registers", Description = "Coaching on correct completion of registers" },
				new ActivityList { Id = 87, Name = "Participate in PMTCT forums and PNC Forums ", Description = "Participate in PMTCT forums and PNC Forums " },
				new ActivityList { Id = 88, Name = "Active participation in Data Management platforms", Description = "Active participation in all Data Management platforms" },
				new ActivityList { Id = 89, Name = "TA support", Description = "TA support: training and support of DOH staff in facilities. strengtening current data systems and structures in facilities." },
				new ActivityList { Id = 90, Name = "Conduct adherence club audits and initiate QIP", Description = "Conduct adherence club audits and initiate QIP based on findings" },
				new ActivityList { Id = 91, Name = "Provide DSD to improve same day initiations", Description = "Provide DSD to improve same day initiations" },
				new ActivityList { Id = 92, Name = "Integrate Case mangement tool", Description = "Integrate Case mangement tool with Facility systems and processes." },
				new ActivityList { Id = 93, Name = "Support PHDC", Description = "Support PHDC: with Human Resources,Improve Linkage and retention,comprehensive patient Care; Cross Referencing of data and generation of reports." },
				new ActivityList { Id = 94, Name = "Improve data-consolidate multiple entries", Description = "Improvement of Facility level Data-consolidate multiple entries into a unique ID (HPRN)" },
				new ActivityList { Id = 95, Name = "Provide support on coaching and mentoring", Description = "Provide ongoing support on coaching and mentoring of DOH / CCT NIMART nurses to scale up same day initiations" },
				new ActivityList { Id = 96, Name = "Support the re-authorization of NIMART nurses", Description = "Support the re-authorization of NIMART nurses" },
				new ActivityList { Id = 97, Name = "Support Mentors to complete NIMART training", Description = "Support DoH and CCT Mentors to complete NIMART training  for  professional nurses  according to Western Cape guidelines/criteria" },
				new ActivityList { Id = 98, Name = "Identify gaps per program operations requirement", Description = "Identify gaps at Facilities as per program operations requirement. Support facilities in reaching set targets(both facility & DSP targets) by linking DSD staff to identified sites." },
				new ActivityList { Id = 99, Name = "Build data/admin staff to support best practices", Description = "Build  capacity of facility data/admin staff to support best practices/national /provincial guidelines on patient record keeping/ filing,archiving, registry hygiene" },
				new ActivityList { Id = 100, Name = "Provide DSD to improve patient experience", Description = "Provide DSD to improve patient  experience and flow through facilities. Increased number of patient medication pick-up points" },
				new ActivityList { Id = 101, Name = "Improve pharmacy waiting times.", Description = "Support decanting strategy to improve pharmacy waiting times." },
				new ActivityList { Id = 102, Name = "Strenthgthening appointment system", Description = "Strenthgthening appointment system in all Facilities." },
				new ActivityList { Id = 103, Name = "Introduce and support pre-retrieval of folders", Description = "Introduce and support pre-retrieval of folders in all Facilities." },
				new ActivityList { Id = 104, Name = "Provide support to on roll out services", Description = "Provide support to DoH  /CCT on roll out services during extended working hours at identified facilities " },
				new ActivityList { Id = 105, Name = "Support critical posts within the HAST Directorate", Description = "Support critical posts within the HAST Directorate" },
				new ActivityList { Id = 106, Name = "Regular and ongoing feedback with sub structures", Description = "Regular and on-going feedback with sub structures and facilities on progress towards targets" },
				new ActivityList { Id = 107, Name = "Cultivate a culture of accountability", Description = "Cultivate a culture of accountability towards facilities, colleagues and clients." },
				new ActivityList { Id = 108, Name = "Individual performance mornitoring and feedback", Description = "Individual performance mornitoring and feedback done for all staff " },
				new ActivityList { Id = 109, Name = "Provision of value clubs", Description = "Provision of value clubs" },
				new ActivityList { Id = 110, Name = "Support registering of value clubs", Description = "Support registering of value clubs (both facility and community) at supported facilities." },
				new ActivityList { Id = 111, Name = "Tracing patient adherence", Description = "Tracing patient adherence through the other DMOC modalities." },
				new ActivityList { Id = 112, Name = "Ensure newly decanted patients are added to clubs", Description = "Working with facility DOH staff to ensure that newly decanted stable patients are added to existing and/or new clubs at supported facilities." },
				new ActivityList { Id = 113, Name = "Generate Risk of treatment failure client lists", Description = "Generation of  Risk of treatment failure client lists to identify gaps and to guide program on resource deployment." },
				new ActivityList { Id = 114, Name = "Weekly Tracking and recall of clients", Description = "Weekly Tracking and recall of clients  with virologic failure using Facility Information Systems " },
				new ActivityList { Id = 115, Name = "Suport with Telephonic tracing and recalls VL", Description = "Suport Facilities with  Telephonic tracing and recalls of  for Viral loads(VL) due; missed VLs and  unsuppressed VL's" },
				new ActivityList { Id = 116, Name = "Improve clinical management", Description = "Improve clinical management  by providing on site facility training and mentoring of clinical staff" },
				new ActivityList { Id = 117, Name = "Support Facilities with Folder Audits", Description = "Support Facilities with Folder Audits to maintain good quality of clinical care and improve VL uptake at Faclity level" },
				new ActivityList { Id = 118, Name = "Support with providing Advanced clinical care", Description = "Support Specialised services by providing Advanced clinical care  ( ROTF, pharmacovigilance) " },
				new ActivityList { Id = 119, Name = "Track VL done on ALL new patients", Description = "Track VL done on ALL new patients tthough implementation and monitoring of the 100 day Case Management at Siyenza Facilities" },
				new ActivityList { Id = 120, Name = "Strengthen viral load monitoring and capturing", Description = "Strengthen viral load monitoring, and capturing  by providing techinal assistance." },
				new ActivityList { Id = 121, Name = "Mobilize individuals with virologic failure", Description = "Mobilize individuals with virologic failure using TIER.net and NHLS and PHCD(Viral load for action reports)" },
				new ActivityList { Id = 122, Name = "Support by providing Advanced clinical care", Description = "Support Specialised services by providing Advanced clinical care for  v  ( ROTF, pharmacovigilance and other co-morbidities)" },
				new ActivityList { Id = 123, Name = "Support care rentention - telephonic tracing", Description = "Support retention in care through telephonic tracing" },
				new ActivityList { Id = 124, Name = "Support care rentention - trace and track", Description = "Support rentention in care through trace and track" },
				new ActivityList { Id = 125, Name = "Support care rentention - improve VL uptake", Description = "Support rentention in care by imprving VL uptake and monitoring" },
				new ActivityList { Id = 126, Name = "Support care rentention - welcome back campaigns", Description = "Support rententions in care through welcome back campaigns" },
				new ActivityList { Id = 127, Name = "Support care retention - pharmacy collection data", Description = "Support retention in care through effective used of pharmacy collection data" },
				new ActivityList { Id = 128, Name = "Support care retention - decanting strategies", Description = "Support retention in care by supporting facilities in decanting strategies" },
				new ActivityList { Id = 129, Name = "Support care rentention - scripting, planning, etc", Description = "Support rentention in care by supporting facilities with scripting, planning  and improving adherence clubs" },
				new ActivityList { Id = 130, Name = "Provide appropriate number of clinicians on ART", Description = "Provide appropriate number of clinicians to facilities to initiate Clients on ART" },
				new ActivityList { Id = 131, Name = "Provide cross reference to track ART initiations", Description = "Provide cross reference between data sytems to track ART initiations" },
				new ActivityList { Id = 132, Name = "Build capacity of staff with NIMART mentoring", Description = "Build capacity of DoH/CCT staff by supporting NIMART mentoring" },
				new ActivityList { Id = 133, Name = "Support DoH/ CCT policy on same day initiations", Description = "Support DoH/ CCT policy on same day initiations" },
				new ActivityList { Id = 134, Name = "Support TLD transition ", Description = "Support TLD transition " },
				new ActivityList { Id = 135, Name = "Provide capacity to sustain medication dispensing", Description = "Provide capacity to sustain medication dispensing to support same day initiation / ART enrolment" },
				new ActivityList { Id = 136, Name = "Identify ART initiation backlogs", Description = "Identify ART initiation backlogs per facility trough weekly data evaluation meetings for identification of gaps at facility level through DSD" },
				new ActivityList { Id = 137, Name = "Provide case managers", Description = "Provide case managers to ensure effective linkage and retention in care." },
				new ActivityList { Id = 138, Name = "Increase access to care", Description = "Increase access to care by expanding pharmacy services into quick pick up points" },
				new ActivityList { Id = 139, Name = "Support people at risk of lost to follow up", Description = "Support to people who are at risk of lost to follow up " },
				new ActivityList { Id = 140, Name = "Support the DOH Welcome Back Campaign", Description = "Support the DOH Welcome Back Campaign" },
				new ActivityList { Id = 141, Name = "Develop IT support for tracking of ARV clients", Description = "Develop IT support for for tracking of ARV clients for reporting to funders" },
				new ActivityList { Id = 142, Name = "Provide  NIMART trained nurses ", Description = "Provide  NIMART trained nurses " },
				new ActivityList { Id = 143, Name = "Provide Advanced Clinical Care by Medical Officers", Description = "Provide  Advanced Clinical Care by Medical Officers" },
				new ActivityList { Id = 144, Name = "Support facilities to reach HAST program", Description = "Support facilities to reach HAST program" },
				new ActivityList { Id = 145, Name = "Provide NIMART mentoring support", Description = "Provide NIMART mentoring support" },
				new ActivityList { Id = 146, Name = "Training on clinical guideline ", Description = "Training on clinical guideline " },
				new ActivityList { Id = 147, Name = "Support with improvement of the HAST core programs", Description = "Support Facilities in sustained improvement of the HAST core program indicators ( ICT,SDI, TLD, TPT, Decanting) through regular update and review of Facility Improvement Plans" },
				new ActivityList { Id = 148, Name = "Support with tracking & Recall of Waiting on ART", Description = "Support Facilities with Weekly tracking and Recall of Waiting on ART to improve linkage to care and number of ART initiations." },
				new ActivityList { Id = 149, Name = "Improve retention in care at supported Facilities", Description = "Improve retention in care at supported Facilitied through daily and weekly tracking of missed appointments and uLTFU" },
				new ActivityList { Id = 150, Name = "Facilitate Weekly Data reviews", Description = "Facilitate Weekly Data reviews as supported Siyenza Facilities to identify ART initiation and retention gaps." },
				new ActivityList { Id = 151, Name = "Facilitate linkage to care", Description = "Facilitate linkage to care" },
				new ActivityList { Id = 152, Name = "Offering targeted HIV testing", Description = "Offering targeted HIV testing" },
				new ActivityList { Id = 153, Name = "Provide counsellors", Description = "Provide counsellors" },
				new ActivityList { Id = 154, Name = "Targeted HIV testing at ANC, TB,PNC,FP,STI points", Description = "Targeted HIV testing at ANC, TB,PNC,FP,STI points" },
				new ActivityList { Id = 155, Name = "Conduct HIV and TB screening", Description = "Conduct HIV and TB screening as part of infacility health screening" },
				new ActivityList { Id = 156, Name = "Facilitate Index Case Finding of sexual partners", Description = "Facilitate Index Case Finding of sexual partners and biological children for all HIV positive clients through facility and community" },
				new ActivityList { Id = 157, Name = "Support DoH's roll out of HIV Self Screening", Description = "Support the Provincial Department of Health's roll out of HIV Self Screening and Index Case Testing " },
				new ActivityList { Id = 158, Name = "Support RTCQI training to counsellors and nurses", Description = "Support RTCQI training to ALL counsellors and nurses" },
				new ActivityList { Id = 159, Name = "Conduct 6 monthly internal SPI-RT assessments", Description = "Conduct 6 monthly internal SPI-RT assessments" },
				new ActivityList { Id = 160, Name = "Support weekly QC and 6 monthly testing", Description = "Support weekly independent QC and 6 monthly proficiency testing" },
				new ActivityList { Id = 161, Name = "Digitizing and analysing of HTS capturing", Description = "Digitizing and analysing of HTS capturing on current data systems" },
				new ActivityList { Id = 162, Name = "Identify with Province and City skills shortage", Description = "Identify with Province and City skills shortage, M&E gaps for reporting and capturing and assist with temporary workforce relief" },
				new ActivityList { Id = 163, Name = "Provide and distribute HTS support equipment", Description = "Provide and distribute HTS support equipment to enable Counsellors and HTS Testers in testing functions " },
				new ActivityList { Id = 164, Name = "Provide HTS in ER, triage settings", Description = "Provide HTS in ER, triage settings in identified District hospitals." },
				new ActivityList { Id = 165, Name = "Provide track and tracing for HIV positive clients", Description = "Provide track and tracing for HIV positive clients in District hospitals for in-patients." },
				new ActivityList { Id = 166, Name = "Strenghthen ICT support", Description = "Strenghthen ICT support through NIMART nurse involvement" },
				new ActivityList { Id = 167, Name = "Support Implementation and upscaling of Run Charts", Description = "Support Implementation and upscaling  of Run Charts as a Quality assurance and Quality improvement tool for HTS,HTS Pos and ICT" },
				new ActivityList { Id = 168, Name = "Violence screening", Description = "Violence screening" },
				new ActivityList { Id = 169, Name = "Men Workplace Testing HIV Testing ", Description = "Men Workplace Testing HIV Testing " },
				new ActivityList { Id = 170, Name = "Finding Youth TVET Testing", Description = "Finding Youth TVET Testing: In partnership with HEAIDS, Anova will continue testing at TVETs colleges in the Cape Metro. STI and TB screening will also be offered." },
				new ActivityList { Id = 171, Name = "Targeting Male Dominated Community HIV  Testing", Description = "Targeting Male Dominated Community HIV  Testing" },
				new ActivityList { Id = 172, Name = "Defaulter Tracking ICT ", Description = "Defaulter Tracking ICT " },
				new ActivityList { Id = 173, Name = "Targeted Wellness Outreaches", Description = "Targeted Wellness Outreaches in Partnership with other community NPOs" },
				new ActivityList { Id = 174, Name = "Following all pregnant women in high burden areas", Description = "Following all pregnant women in high burden areas" },
				new ActivityList { Id = 175, Name = "BCI - Behaviour Change Interventions", Description = "BCI - Behaviour Change Interventions" },
				new ActivityList { Id = 176, Name = "Condom distribution", Description = "Condom distribution" },
				new ActivityList { Id = 177, Name = "Needle and syringe distribution", Description = "Needle and syringe distribution" },
				new ActivityList { Id = 178, Name = "Opioid Substitution Treatment (OST)", Description = "Opioid Substitution Treatment (OST)" },
				new ActivityList { Id = 179, Name = "STI screening", Description = "STI screening" },
				new ActivityList { Id = 180, Name = "TB screening", Description = "TB screening" },
				new ActivityList { Id = 181, Name = "Family Planning", Description = "Family Planning" },
				new ActivityList { Id = 182, Name = "ART", Description = "ART" },
				new ActivityList { Id = 183, Name = "Pregnancy testing", Description = "Pregnancy testing" },
				new ActivityList { Id = 184, Name = "non communable disease screening", Description = "non communable disease screening" },
				new ActivityList { Id = 185, Name = "Referrals to DOH/COCT facilities", Description = "Referrals to DOH/COCT facilities" },
				new ActivityList { Id = 186, Name = "TB testing", Description = "TB testing" },
				new ActivityList { Id = 187, Name = "Human Rights violations screening", Description = "Human Rights violations screening" },
				new ActivityList { Id = 188, Name = "Overdose management / awareness", Description = "Overdose management / awareness" },
				new ActivityList { Id = 189, Name = "Hepatitis C sceening, diagnosis and treatment ", Description = "Hepatitis C sceening, diagnosis and treatment " },
				new ActivityList { Id = 190, Name = "Hepatitis B testing and vaccination", Description = "Hepatitis B testing and vaccination" },
				new ActivityList { Id = 191, Name = "Sensitisation training", Description = "Sensitisation training" },
				new ActivityList { Id = 192, Name = "Health: HIV Testing", Description = "Health: HIV Testing" },
				new ActivityList { Id = 193, Name = "Health: HIV Self Screening", Description = "Health: HIV Self Screening" },
				new ActivityList { Id = 194, Name = "Health: Male/Female Condom and Lube Distribution", Description = "Health: Male/Female Condom and Lube Distribution" },
				new ActivityList { Id = 195, Name = "Health: STI screening and Investigation", Description = "Health: STI screening and Investigation" },
				new ActivityList { Id = 196, Name = "Health: TB Screening and TB Sputum testing", Description = "Health: TB Screening and TB Sputum testing" },
				new ActivityList { Id = 197, Name = "Health: Pregnancy Testing", Description = "Health: Pregnancy Testing" },
				new ActivityList { Id = 198, Name = "Health: SRH", Description = "Health: SRH" },
				new ActivityList { Id = 199, Name = "Health: ART", Description = "Health: ART" },
				new ActivityList { Id = 200, Name = "Health: PrEP related lab costs", Description = "Health: PrEP related lab costs" },
				new ActivityList { Id = 201, Name = "Health: Emergency Contraception", Description = "Health: Emergency Contraception" },
				new ActivityList { Id = 202, Name = "Behaviour Change: Peer Education", Description = "Behaviour Change: Peer Education" },
				new ActivityList { Id = 203, Name = "Behaviour Change:Comprehensive Sexuality Education", Description = "Behaviour Change:Comprehensive Sexuality Education" },
				new ActivityList { Id = 204, Name = "Behaviour Change: Individual Psycho Social Support", Description = "Behaviour Change: Individual Psycho Social Support" },
				new ActivityList { Id = 205, Name = "Behaviour Change: PrEP Demand Creation", Description = "Behaviour Change: PrEP Demand Creation" },
				new ActivityList { Id = 206, Name = "Behaviour Change: Teen Parenting/Parenting", Description = "Behaviour Change: Teen Parenting/Parenting" },
				new ActivityList { Id = 207, Name = "Behaviour Change: Teen & Caregiver Comunication", Description = "Behaviour Change: Teen & Caregiver Comunication" },
				new ActivityList { Id = 208, Name = "Behaviour Change: SRH Knowledge and behaviour", Description = "Behaviour Change: SRH Knowledge and behaviour" },
				new ActivityList { Id = 209, Name = "Behaviour Change: GBV Prevention", Description = "Behaviour Change: GBV Prevention" },
				new ActivityList { Id = 210, Name = "Behaviour Change: Adherence Support", Description = "Behaviour Change: Adherence Support (Mental Health Support)" },
				new ActivityList { Id = 211, Name = "Behaviour Change: Physical activity", Description = "Behaviour Change: Physical activity" },
				new ActivityList { Id = 212, Name = "Structural: Support to Access Grants", Description = "Structural: Support to Access Grants" },
				new ActivityList { Id = 213, Name = "Structural: Dignity Packs", Description = "Structural: Dignity Packs" },
				new ActivityList { Id = 214, Name = "Structural: Academic Support and Career Guidance", Description = "Structural: Academic Support and Career Guidance" },
				new ActivityList { Id = 215, Name = "Structural: Return to School Support", Description = "Structural: Return to School Support" },
				new ActivityList { Id = 216, Name = "Structural: ECD Vouchers", Description = "Structural: ECD Vouchers" },
				new ActivityList { Id = 217, Name = "Structural: GBV Awareness and Self-Defence", Description = "Structural: GBV Awareness and Self-Defence" },
				new ActivityList { Id = 218, Name = "Structural: Economic Strengthening", Description = "Structural: Economic Strengthening" },
				new ActivityList { Id = 219, Name = "Trauma containment", Description = "Trauma containment" },
				new ActivityList { Id = 220, Name = "Risk assessment & referral; ", Description = "Risk assessment & referral; " },
				new ActivityList { Id = 221, Name = "Follow-up psychosocial support", Description = "Follow-up psychosocial support" },
				new ActivityList { Id = 222, Name = "PEP adherence suppor", Description = "PEP adherence suppor" },
				new ActivityList { Id = 223, Name = "Role out of HIV SS", Description = "Role out of HIV SS" },
				new ActivityList { Id = 224, Name = "Referral for other social support services", Description = "Referral for other social support services" },
				new ActivityList { Id = 225, Name = "Court preparation & support", Description = "Court preparation & support" },
				new ActivityList { Id = 226, Name = "GBV awareness & community outreach", Description = "GBV awareness & community outreach" },
				new ActivityList { Id = 227, Name = "PrEP Demand Creation and referrals to PrEP Clinics", Description = "PrEP Demand Creation and referrals to PrEP Clinics" },
				new ActivityList { Id = 228, Name = "Delivery of Chronic Medication", Description = "Delivery of Chronic Medication" },
				new ActivityList { Id = 229, Name = "COVID response", Description = "COVID response" },
				new ActivityList { Id = 230, Name = "COVID testing", Description = "COVID testing" },
				new ActivityList { Id = 231, Name = "COVID vaccination", Description = "COVID vaccination" },
				new ActivityList { Id = 232, Name = "COVID vaccine demand creation", Description = "COVID vaccine demand creation" },
				new ActivityList { Id = 233, Name = "COVID tracking and tracing", Description = "COVID tracking and tracing" },
				new ActivityList { Id = 234, Name = "Establish peer groups for Mental Health", Description = "Establish peer groups for Mental Health" },
				new ActivityList { Id = 235, Name = "Patient transport support", Description = "Patient transport support" },
				new ActivityList { Id = 236, Name = "Telehealth support", Description = "Telehealth support" }
			);
		}
	}
}
